/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Fractal.java
 *
 * Created on 11-02-2012, 12:05:58 AM
 */

package com.fractales;

/**
 *
 * @author claudio
 */
public class Fractal extends java.applet.Applet {

    /** Initializes the applet Fractal */
    public void init() {
        try {
            java.awt.EventQueue.invokeAndWait(new Runnable() {
                public void run() {
                    initComponents();
                }
            });
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    /** This method is called from within the init() method to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
